name: cicd

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  ci:
    runs-on: ubuntu-latest

    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate commit id
        id: commit
        shell: bash
        run: |
          echo "commit_id=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT

      - name: Debug commit id
        run: echo "Commit ID is ${{ steps.commit.outputs.commit_id }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: luc09/${{ github.event.repository.name }}:${{ steps.commit.outputs.commit_id }}

  cd:
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug commit from CI
        run: echo "Commit from CI: ${{ needs.ci.outputs.commit_id }}"

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Update Helm values
        run: |
          yq -Yi ".image.tag = \"${{ needs.ci.outputs.commit_id }}\"" \
            charts/${{ github.event.repository.name }}/values-dev.yaml

      - name: Show updated values
        run: |
          cat charts/${{ github.event.repository.name }}/values-dev.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image tag to ${{ needs.ci.outputs.commit_id }}"

      - name: Install ArgoCD CLI
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Login to ArgoCD
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Ensure ArgoCD repo and app
        run: |
          APP_NAME=${{ github.event.repository.name }}
          REPO_URL="https://github.com/aarsh-mishra-exp/$APP_NAME.git"

          argocd repo list | grep -q $REPO_URL || argocd repo add $REPO_URL

          argocd app get $APP_NAME || argocd app create $APP_NAME \
            --repo $REPO_URL \
            --path charts/$APP_NAME \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Sync ArgoCD app
        run: |
          APP_NAME=${{ github.event.repository.name }}
          argocd app sync $APP_NAME
          argocd app wait $APP_NAME --timeout 180
